changes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -73,11 +73,25 @@ jobs:
         uses: ./dist/apps/affected
         with:
           rules: |
+            peggy-parser-updated: 'apps/affected/src/parser.peggy';
+            peggy-parser-updates-incomplete: parser-peggy-updated AND !('apps/affected/src/parser.ts' OR 'e2e/src/affected/parser.spec.ts');
             ci: '.github/workflows/ci.yml';
             [affected]: './apps/affected/**' './dist/apps/affected/**';
             [version-autopilot]: './apps/version-autopilot/**' './dist/apps/version-autopilot/**';
             [pragma]: './apps/pragma/**' './dist/apps/pragma/**';
-            e2e: './e2e/**' ci pragma affected version-autopilot !'**/*.md';
+            e2e: ('./e2e/**' ci pragma affected version-autopilot) EXCEPT ('**/*.md');
+
+      - name: incomplete parser changes
+        if: ${{ !failure() && !cancelled() && fromJson(steps.affected.outputs.affected).changes.peggy-parser-updates-incomplete }}
+        run: |
+          echo "Missing parser.ts or parser.spec.ts in changeset."
+          exit 1
+
+      - name: check if parser changes are incomplete
+        if: ${{ !failure() && !cancelled() && fromJson(steps.affected.outputs.affected).changes.peggy-parser-updated }}
+        run: |
+          pnpm apps:affected:generate-parser
+          git diff --exit-code -- ./
 
       - name: e2e tests
         if: ${{ !failure() && !cancelled() && fromJson(steps.affected.outputs.affected).changes.e2e }}
